# this will show up on the tab for the site
meta-title: "josh  |  brugman"
# this shows up below the title in a google search result
meta-description: This is an example of the description
# whether to show the title on the front page
show-title: true
# this shows up on the main page
title: "josh | brugman"
# whether to show the background image or not

# if you would like to show images on the main page put them in the user-images folder and then include them here
# the alt is what will show when you hover over the image with a cursor
images:

- alt: Logo
  url: pt-handwritten-black.png

- alt: Bio photo
  url: pt-bio-photo.png